#!/bin/sh
#
# PROVIDE: subsonic
# REQUIRE: LOGIN DAEMON NETWORKING
# KEYWORD: shutdown
#
# To enable subsonic, add this line to your /etc/rc.conf:
#
# subsonic_enable="YES"
#
# And optionally these line:
#
# subsonic_user="username" # Default is "root"
# subsonic_bin="/path/to/subsonic.sh" # Default is "/usr/local/sbin/subsonic.sh"
 
. /etc/rc.subr
 
name="subsonic"
rcvar="subsonic_enable"
 
load_rc_config $name
 
required_files=$subsonic_bin
 
: ${subsonic_enable="NO"}
: ${subsonic_user="root"}
: ${subsonic_bin="/usr/local/subsonic/standalone/subsonic.sh"}
: ${subsonic_music_folder="/mnt/media/music"}
: ${subsonic_podcast_folder="/mnt/media/podcasts"}
: ${subsonic_playlist_folder="/mnt/media/playlists"}
 
command=$subsonic_bin
command_args="--home=/usr/local/subsonic --default-music-folder=/mnt/media/music --default-podcast-folder=/mnt/media/podcasts --default-playlist-folder=/mnt/media/playlists"

run_rc_command "$1"