#!/bin/sh
#
# PROVIDE: subsonic
# REQUIRE: LOGIN DAEMON NETWORKING
# KEYWORD: shutdown
#
# To enable subsonic, add this line to your /etc/rc.conf:
#
# subsonic_enable="YES"
#
# And optionally these line:
#
# subsonic_user="username" # Default is "root"
# subsonic_bin="/path/to/subsonic.sh" # Default is "/usr/local/sbin/subsonic.sh"
 
. /etc/rc.subr
 
name="subsonic"
rcvar="subsonic_enable"
 
load_rc_config $name
 
required_files=$subsonic_bin
 
: ${subsonic_enable="NO"}
: ${subsonic_user="root"}
: ${subsonic_port="4040"}
: ${subsonic_home="/usr/local/subsonic"}
: ${subsonic_bin="${subsonic_home}/subsonic.sh"}
: ${subsonic_music_folder="/mnt/media/music"}
: ${subsonic_podcast_folder="/mnt/media/music/podcasts"}
: ${subsonic_playlist_folder="/mnt/media/music/playlists"}
: ${subsonic_pidfile="${subsonic_home}/subsonic.pid"

status_cmd="${name}_status"
stop_cmd="${name}_stop"

command=$subsonic_bin
command_args="--pidfile=${subsonic_pidfile} --home=${subsonic_home} --port={subsonic_port} --default-music-folder=${subsonic_music_folder} --default-podcast-folder=${subsonic_podcast_folder} --default-playlist-folder=${subsonic_playlist_folder}"

verify_pid() {
    pid=`cat ${subsonic_pidfile} 2>/dev/null`
    ps -p ${pid} | grep -q "subsonic"
    return $?
}

subsonic_stop() {
    echo "Stopping ${name}"
    verify_pid
    if [ -n "${pid}" ]; then
        kill ${sig_stop} ${pid}
        wait_for_pids ${pid}
        echo "Stopped"
    fi
}

subsonic_status() {
    verify_pid && echo "${name} is running as ${pid}" || echo "${name} is not running"
}

run_rc_command "$1"